name: gliders
description: easy to manage your gliders.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.0.2
  cupertino_icons: ^1.0.5
  firebase_auth: ^4.0.2
  firebase_core: ^2.1.0
  firebase_storage: ^11.0.2
  fl_chart: ^0.55.2
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.0.2
  flutter_screenutil: ^5.5.4
  flutter_staggered_grid_view: ^0.6.2
  freezed_annotation: ^2.1.0
  gallery_saver: ^2.3.2
  go_router: ^5.0.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  hexcolor: ^3.0.1
  image: ^3.2.2
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  just_the_tooltip: ^0.0.12
  logger: ^1.1.0
  mobile_scanner: ^2.0.0
  path_provider: ^2.0.11
  qr_flutter: ^4.0.0
  share_plus: ^6.0.1
  shared_preferences: ^2.0.15
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.3

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icons/ic_logo_app.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
